### ISSUE TITLE
当我用docker 启动多个实例后，登录到swagger，调用不同实例的接口后会抛出以下警告

### ISSUE THREAD

**Issue by LCZQY** [anjoy8/Blog.Core#361]
`Error unprotecting the session cookie.
System.Security.Cryptography.CryptographicException: The key {cb2affcd-2b20-482d-9e79-602bc4b5868d} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)`
![image](https://github.com/anjoy8/Blog.Core/assets/35684519/3053b473-f791-4e35-8afd-74bae1118fa3)

**Comment by LCZQY** [comment]
有用Redis 没有把session信息存入redis 哦
